# Generated by Django 4.0.3 on 2022-03-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(blank=True)),
                ('account_name', models.CharField(default='', max_length=30)),
                ('description', models.CharField(default='', max_length=100)),
                ('account_type', models.CharField(default='', max_length=30)),
                ('opening_balance', models.CharField(default='', max_length=30)),
                ('current_balance', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
